version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend
  
  redis-stack:
    image: redis-stack:latest
    networks:
      - backend

  my-project:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis-stack
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - my-project
    networks:
      - frontend
  

